# Generated by Django 4.2.16 on 2024-12-20 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_team_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('opis', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Stanowiska',
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='website',
        ),
        migrations.AddField(
            model_name='person',
            name='firstname',
            field=models.CharField(default='Jan', max_length=60, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='lastname',
            field=models.CharField(default='Kowalski', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Choose your Team', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.team'),
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('plec', models.CharField(choices=[('k', 'kobieta'), ('m', 'mężczyzna'), ('i', 'inne')], default='k', max_length=1)),
                ('data_dodania', models.DateField(auto_now_add=True)),
                ('stanowisko', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='myapp.stanowisko')),
            ],
            options={
                'verbose_name_plural': 'Osoby',
            },
        ),
    ]
